INSERT INTO specialization values (1, 'Business analyst' );
INSERT INTO specialization values (2, 'Security' );
INSERT INTO specialization values (3, 'java basis' );
INSERT INTO specialization values (4, 'java verdieping');
INSERT INTO specialization values (5, 'front end development' );
INSERT INTO specialization values (6, 'COBOL' );
INSERT INTO specialization values (7, 'C#' );
INSERT INTO specialization values (8, 'UML' );
INSERT INTO specialization values (9, 'SQL foundation' );
INSERT INTO specialization values (10, 'SQL / DBA' );
INSERT INTO specialization values (11, 'ITIL' );
INSERT INTO specialization values (12, 'ASL' );